#!/bin/bash
# --- Script generated by step_generate_download_script.py ---
# Ensure you have gsutil installed and authenticated (gcloud auth login)

mkdir -p data/raw_audio
cd data/raw_audio

# Downloading 825780
echo "Downloading 825780 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/967179/825780_audio.wav" "825780.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 825780. Check gsutil setup/permissions."
fi

# Downloading 825727
echo "Downloading 825727 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/967179/825727_audio.wav" "825727.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 825727. Check gsutil setup/permissions."
fi

# Downloading 988596
echo "Downloading 988596 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/1147542/988596_audio.wav" "988596.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 988596. Check gsutil setup/permissions."
fi

# Downloading 990175
echo "Downloading 990175 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/1147542/990175_audio.wav" "990175.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 990175. Check gsutil setup/permissions."
fi

# Downloading 526266
echo "Downloading 526266 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/639950/526266_audio.wav" "526266.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 526266. Check gsutil setup/permissions."
fi

# Downloading 520199
echo "Downloading 520199 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/639950/520199_audio.wav" "520199.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 520199. Check gsutil setup/permissions."
fi

# Downloading 542785
echo "Downloading 542785 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/608692/542785_audio.wav" "542785.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 542785. Check gsutil setup/permissions."
fi

# Downloading 494019
echo "Downloading 494019 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/608692/494019_audio.wav" "494019.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 494019. Check gsutil setup/permissions."
fi

# Downloading 523045
echo "Downloading 523045 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/642712/523045_audio.wav" "523045.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 523045. Check gsutil setup/permissions."
fi

# Downloading 522951
echo "Downloading 522951 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/642712/522951_audio.wav" "522951.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 522951. Check gsutil setup/permissions."
fi

# Downloading 254219
echo "Downloading 254219 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/360731/254219_audio.wav" "254219.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 254219. Check gsutil setup/permissions."
fi

# Downloading 253253
echo "Downloading 253253 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/360731/253253_audio.wav" "253253.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 253253. Check gsutil setup/permissions."
fi

# Downloading 351501
echo "Downloading 351501 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/460517/351501_audio.wav" "351501.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 351501. Check gsutil setup/permissions."
fi

# Downloading 350606
echo "Downloading 350606 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/460517/350606_audio.wav" "350606.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 350606. Check gsutil setup/permissions."
fi

# Downloading 629904
echo "Downloading 629904 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/755894/629904_audio.wav" "629904.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 629904. Check gsutil setup/permissions."
fi

# Downloading 635909
echo "Downloading 635909 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/755894/635909_audio.wav" "635909.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 635909. Check gsutil setup/permissions."
fi

# Downloading 989901
echo "Downloading 989901 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/1147324/989901_audio.wav" "989901.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 989901. Check gsutil setup/permissions."
fi

# Downloading 990783
echo "Downloading 990783 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/1147324/990783_audio.wav" "990783.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 990783. Check gsutil setup/permissions."
fi

# Downloading 240907
echo "Downloading 240907 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/347326/240907_audio.wav" "240907.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 240907. Check gsutil setup/permissions."
fi

# Downloading 240909
echo "Downloading 240909 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/347326/240909_audio.wav" "240909.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 240909. Check gsutil setup/permissions."
fi

# Downloading 270153
echo "Downloading 270153 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/378001/270153_audio.wav" "270153.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 270153. Check gsutil setup/permissions."
fi

# Downloading 270150
echo "Downloading 270150 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/378001/270150_audio.wav" "270150.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 270150. Check gsutil setup/permissions."
fi

# Downloading 475392
echo "Downloading 475392 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/592421/475392_audio.wav" "475392.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 475392. Check gsutil setup/permissions."
fi

# Downloading 475356
echo "Downloading 475356 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/592421/475356_audio.wav" "475356.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 475356. Check gsutil setup/permissions."
fi

# Downloading 255349
echo "Downloading 255349 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/362814/255349_audio.wav" "255349.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 255349. Check gsutil setup/permissions."
fi

# Downloading 255381
echo "Downloading 255381 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/362814/255381_audio.wav" "255381.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 255381. Check gsutil setup/permissions."
fi

# Downloading 767685
echo "Downloading 767685 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/902397/767685_audio.wav" "767685.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 767685. Check gsutil setup/permissions."
fi

# Downloading 767869
echo "Downloading 767869 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/902397/767869_audio.wav" "767869.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 767869. Check gsutil setup/permissions."
fi

# Downloading 886193
echo "Downloading 886193 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/1032369/886193_audio.wav" "886193.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 886193. Check gsutil setup/permissions."
fi

# Downloading 888331
echo "Downloading 888331 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/1032369/888331_audio.wav" "888331.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 888331. Check gsutil setup/permissions."
fi

# Downloading 615351
echo "Downloading 615351 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/741178/615351_audio.wav" "615351.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 615351. Check gsutil setup/permissions."
fi

# Downloading 615319
echo "Downloading 615319 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/741178/615319_audio.wav" "615319.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 615319. Check gsutil setup/permissions."
fi

# Downloading 738845
echo "Downloading 738845 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/870590/738845_audio.wav" "738845.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 738845. Check gsutil setup/permissions."
fi

# Downloading 739630
echo "Downloading 739630 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/870590/739630_audio.wav" "739630.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 739630. Check gsutil setup/permissions."
fi

# Downloading 272241
echo "Downloading 272241 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/379319/272241_audio.wav" "272241.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 272241. Check gsutil setup/permissions."
fi

# Downloading 282447
echo "Downloading 282447 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/379319/282447_audio.wav" "282447.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 282447. Check gsutil setup/permissions."
fi

# Downloading 270296
echo "Downloading 270296 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/378238/270296_audio.wav" "270296.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 270296. Check gsutil setup/permissions."
fi

# Downloading 270291
echo "Downloading 270291 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/378238/270291_audio.wav" "270291.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 270291. Check gsutil setup/permissions."
fi

# Downloading 365033
echo "Downloading 365033 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/475992/365033_audio.wav" "365033.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 365033. Check gsutil setup/permissions."
fi

# Downloading 365059
echo "Downloading 365059 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/475992/365059_audio.wav" "365059.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 365059. Check gsutil setup/permissions."
fi

# Downloading 661889
echo "Downloading 661889 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/786720/661889_audio.wav" "661889.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 661889. Check gsutil setup/permissions."
fi

# Downloading 661767
echo "Downloading 661767 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/786720/661767_audio.wav" "661767.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 661767. Check gsutil setup/permissions."
fi

# Downloading 239492
echo "Downloading 239492 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/346081/239492_audio.wav" "239492.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 239492. Check gsutil setup/permissions."
fi

# Downloading 241695
echo "Downloading 241695 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/346081/241695_audio.wav" "241695.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 241695. Check gsutil setup/permissions."
fi

# Downloading 350297
echo "Downloading 350297 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/460430/350297_audio.wav" "350297.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 350297. Check gsutil setup/permissions."
fi

# Downloading 350347
echo "Downloading 350347 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/460430/350347_audio.wav" "350347.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 350347. Check gsutil setup/permissions."
fi

# Downloading 269794
echo "Downloading 269794 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/377371/269794_audio.wav" "269794.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 269794. Check gsutil setup/permissions."
fi

# Downloading 269383
echo "Downloading 269383 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/377371/269383_audio.wav" "269383.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 269383. Check gsutil setup/permissions."
fi

# Downloading 240994
echo "Downloading 240994 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/346088/240994_audio.wav" "240994.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 240994. Check gsutil setup/permissions."
fi

# Downloading 243702
echo "Downloading 243702 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/346088/243702_audio.wav" "243702.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 243702. Check gsutil setup/permissions."
fi

# Downloading 537776
echo "Downloading 537776 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/657859/537776_audio.wav" "537776.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 537776. Check gsutil setup/permissions."
fi

# Downloading 537983
echo "Downloading 537983 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/657859/537983_audio.wav" "537983.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 537983. Check gsutil setup/permissions."
fi

# Downloading 630221
echo "Downloading 630221 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/756383/630221_audio.wav" "630221.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 630221. Check gsutil setup/permissions."
fi

# Downloading 630926
echo "Downloading 630926 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/756383/630926_audio.wav" "630926.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 630926. Check gsutil setup/permissions."
fi

# Downloading 583544
echo "Downloading 583544 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/706065/583544_audio.wav" "583544.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 583544. Check gsutil setup/permissions."
fi

# Downloading 583552
echo "Downloading 583552 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/706065/583552_audio.wav" "583552.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 583552. Check gsutil setup/permissions."
fi

# Downloading 584003
echo "Downloading 584003 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/705928/584003_audio.wav" "584003.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 584003. Check gsutil setup/permissions."
fi

# Downloading 583991
echo "Downloading 583991 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/705928/583991_audio.wav" "583991.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 583991. Check gsutil setup/permissions."
fi

# Downloading 978393
echo "Downloading 978393 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/1134557/978393_audio.wav" "978393.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 978393. Check gsutil setup/permissions."
fi

# Downloading 978484
echo "Downloading 978484 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/1134557/978484_audio.wav" "978484.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 978484. Check gsutil setup/permissions."
fi

# Downloading 629868
echo "Downloading 629868 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/756535/629868_audio.wav" "629868.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 629868. Check gsutil setup/permissions."
fi

# Downloading 629862
echo "Downloading 629862 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/756535/629862_audio.wav" "629862.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 629862. Check gsutil setup/permissions."
fi

# Downloading 443952
echo "Downloading 443952 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/557922/443952_audio.wav" "443952.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 443952. Check gsutil setup/permissions."
fi

# Downloading 444282
echo "Downloading 444282 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/557922/444282_audio.wav" "444282.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 444282. Check gsutil setup/permissions."
fi

# Downloading 302506
echo "Downloading 302506 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/411140/302506_audio.wav" "302506.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 302506. Check gsutil setup/permissions."
fi

# Downloading 302503
echo "Downloading 302503 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/411140/302503_audio.wav" "302503.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 302503. Check gsutil setup/permissions."
fi

# Downloading 645534
echo "Downloading 645534 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/772064/645534_audio.wav" "645534.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 645534. Check gsutil setup/permissions."
fi

# Downloading 644742
echo "Downloading 644742 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/772064/644742_audio.wav" "644742.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 644742. Check gsutil setup/permissions."
fi

# Downloading 330457
echo "Downloading 330457 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/427660/330457_audio.wav" "330457.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 330457. Check gsutil setup/permissions."
fi

# Downloading 319431
echo "Downloading 319431 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/427660/319431_audio.wav" "319431.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 319431. Check gsutil setup/permissions."
fi

# Downloading 979497
echo "Downloading 979497 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/1133355/979497_audio.wav" "979497.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 979497. Check gsutil setup/permissions."
fi

# Downloading 977253
echo "Downloading 977253 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/1133355/977253_audio.wav" "977253.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 977253. Check gsutil setup/permissions."
fi

# Downloading 238123
echo "Downloading 238123 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/344590/238123_audio.wav" "238123.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 238123. Check gsutil setup/permissions."
fi

# Downloading 238079
echo "Downloading 238079 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/344590/238079_audio.wav" "238079.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 238079. Check gsutil setup/permissions."
fi

# Downloading 305347
echo "Downloading 305347 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/413003/305347_audio.wav" "305347.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 305347. Check gsutil setup/permissions."
fi

# Downloading 305308
echo "Downloading 305308 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/413003/305308_audio.wav" "305308.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 305308. Check gsutil setup/permissions."
fi

# Downloading 489675
echo "Downloading 489675 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/607477/489675_audio.wav" "489675.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 489675. Check gsutil setup/permissions."
fi

# Downloading 489638
echo "Downloading 489638 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/607477/489638_audio.wav" "489638.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 489638. Check gsutil setup/permissions."
fi

# Downloading 781184
echo "Downloading 781184 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/917675/781184_audio.wav" "781184.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 781184. Check gsutil setup/permissions."
fi

# Downloading 781268
echo "Downloading 781268 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/917675/781268_audio.wav" "781268.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 781268. Check gsutil setup/permissions."
fi

# Downloading 663529
echo "Downloading 663529 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/787986/663529_audio.wav" "663529.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 663529. Check gsutil setup/permissions."
fi

# Downloading 661461
echo "Downloading 661461 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/787986/661461_audio.wav" "661461.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 661461. Check gsutil setup/permissions."
fi

# Downloading 583533
echo "Downloading 583533 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/705932/583533_audio.wav" "583533.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 583533. Check gsutil setup/permissions."
fi

# Downloading 583334
echo "Downloading 583334 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/705932/583334_audio.wav" "583334.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 583334. Check gsutil setup/permissions."
fi

# Downloading 798121
echo "Downloading 798121 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/920224/798121_audio.wav" "798121.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 798121. Check gsutil setup/permissions."
fi

# Downloading 783966
echo "Downloading 783966 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/920224/783966_audio.wav" "783966.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 783966. Check gsutil setup/permissions."
fi

# Downloading 400490
echo "Downloading 400490 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/511971/400490_audio.wav" "400490.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 400490. Check gsutil setup/permissions."
fi

# Downloading 400503
echo "Downloading 400503 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/511971/400503_audio.wav" "400503.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 400503. Check gsutil setup/permissions."
fi

# Downloading 857737
echo "Downloading 857737 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/1001923/857737_audio.wav" "857737.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 857737. Check gsutil setup/permissions."
fi

# Downloading 856801
echo "Downloading 856801 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/1001923/856801_audio.wav" "856801.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 856801. Check gsutil setup/permissions."
fi

# Downloading 301080
echo "Downloading 301080 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/409660/301080_audio.wav" "301080.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 301080. Check gsutil setup/permissions."
fi

# Downloading 301057
echo "Downloading 301057 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/409660/301057_audio.wav" "301057.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 301057. Check gsutil setup/permissions."
fi

# Downloading 367249
echo "Downloading 367249 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/477740/367249_audio.wav" "367249.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 367249. Check gsutil setup/permissions."
fi

# Downloading 366972
echo "Downloading 366972 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/477740/366972_audio.wav" "366972.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 366972. Check gsutil setup/permissions."
fi

# Downloading 269907
echo "Downloading 269907 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/377388/269907_audio.wav" "269907.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 269907. Check gsutil setup/permissions."
fi

# Downloading 270037
echo "Downloading 270037 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/377388/270037_audio.wav" "270037.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 270037. Check gsutil setup/permissions."
fi

# Downloading 319105
echo "Downloading 319105 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/427666/319105_audio.wav" "319105.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 319105. Check gsutil setup/permissions."
fi

# Downloading 319126
echo "Downloading 319126 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/427666/319126_audio.wav" "319126.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 319126. Check gsutil setup/permissions."
fi

# Downloading 754618
echo "Downloading 754618 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/887857/754618_audio.wav" "754618.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 754618. Check gsutil setup/permissions."
fi

# Downloading 753435
echo "Downloading 753435 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/887857/753435_audio.wav" "753435.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 753435. Check gsutil setup/permissions."
fi

# Downloading 1021370
echo "Downloading 1021370 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/1180199/1021370_audio.wav" "1021370.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 1021370. Check gsutil setup/permissions."
fi

# Downloading 1020918
echo "Downloading 1020918 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/1180199/1020918_audio.wav" "1020918.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 1020918. Check gsutil setup/permissions."
fi

# Downloading 840793
echo "Downloading 840793 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/983900/840793_audio.wav" "840793.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 840793. Check gsutil setup/permissions."
fi

# Downloading 840781
echo "Downloading 840781 from GCS..."
gsutil cp "gs://joshtalks-data-collection/hq_data/hi/983900/840781_audio.wav" "840781.wav"
if [ $? -ne 0 ]; then
  echo "[ERROR] gsutil failed for 840781. Check gsutil setup/permissions."
fi

echo "All download commands executed."
